# run the testsuite on travis-ci.com
---
language: C
dist: bionic
sudo: required
arch:
  - amd64
  - ppc64le

script:
  - autoreconf --install
  - mkdir build
  - cd build
  - ../configure
  - make
  - sudo make install
  - cd ..
  - debian/tests/sdate
